[package]
name = "dhcp_server"
version = "0.1.0"
edition = "2024"

[lib]
name = "dhcp_server_lib"
path = "src/lib.rs"

[[bin]]
name = "dhcp_server_bin"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.18"